# Generated by Django 4.0.5 on 2022-06-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagename', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Conatact',
            new_name='Contact',
        ),
    ]
